# Generated by Django 5.2.18 on 2026-10-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='apply_vat',
        ),
        migrations.AddField(
            model_name='document',
            name='served_by',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='document',
            name='vat_mode',
            field=models.CharField(choices=[('exclusive', 'VAT exclusive (add VAT on top)'), ('inclusive', 'VAT inclusive (prices include VAT)'), ('none', 'No VAT')], default='exclusive', max_length=10),
        ),
    ]
