# Generated by Django 5.2.18 on 2026-10-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_apply_vat_document_served_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='business',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
