# Generated by Django 5.2.18 on 2026-10-08 10:36

from django.db import migrations


def freeze(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Profile = apps.get_model("documents", "BusinessProfile")
    p = Profile.objects.first()
    if not p:
        return
    snap = {
        "name": p.name,
        "tagline": p.tagline,
        "address": p.address,
        "phone": p.phone,
        "email": p.email,
        "kra_pin": p.kra_pin,
        "payment_details": p.payment_details,
        "receipt_footer": p.receipt_footer,
        "vat_rate": str(p.vat_rate),
        "logo": p.logo.name or "",
        "signature": p.signature.name or "",
        "stamp": p.stamp.name or "",
    }
    for d in Document.objects.all():
        if not d.business:
            d.business = snap
            d.save(update_fields=["business"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_business"),
    ]

    operations = [
        migrations.RunPython(freeze, migrations.RunPython.noop),
    ]