# Generated by Django 5.2.18 on 2026-10-08 12:15

import django.db.models.deletion
import django.utils.timezone
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_freeze_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='delivery_terms',
            field=models.TextField(blank=True, help_text='Acceptance wording on delivery notes'),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_location', models.CharField(blank=True, max_length=200)),
                ('delivered_by', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('received_by', models.CharField(blank=True, max_length=120)),
                ('signed_copy', models.FileField(blank=True, upload_to=documents.models.signed_path)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.JSONField(blank=True, default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('cable', 'Cable / adapter'), ('other', 'Other')], default='other', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('serial_numbers', models.TextField(blank=True)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.deliverynote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
