# Generated by Django 5.2.18 on 2026-10-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_businessprofile_delivery_terms_deliverynote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('category', models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('cable', 'Cable / adapter'), ('other', 'Other')], default='other', help_text='Sets the delivery checklist used for this item', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('track_stock', models.BooleanField(default=False)),
                ('track_serials', models.BooleanField(default=False, help_text="Registers each unit's serial (turns on stock tracking)", verbose_name='Track serial numbers')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='buyer_pin',
            field=models.CharField(blank=True, max_length=20, verbose_name='Buyer KRA PIN'),
        ),
        migrations.AddField(
            model_name='document',
            name='etims_invoice_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='eTIMS invoice no.'),
        ),
        migrations.AddField(
            model_name='document',
            name='etims_qr',
            field=models.CharField(blank=True, help_text='Paste the QR link or data KRA gives you for this invoice', max_length=500, verbose_name='eTIMS QR data or link'),
        ),
        migrations.AddField(
            model_name='document',
            name='share_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='share_viewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to='documents.product'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('purchase', 'Stock received'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='documents.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='documents.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_serials', to='documents.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='documents.product')),
            ],
            options={
                'ordering': ['serial'],
                'constraints': [models.UniqueConstraint(fields=('product', 'serial'), name='uniq_product_serial')],
            },
        ),
    ]
